add square pcb plated hole
tscircuit/circuit-json pull request #105
Opened 2024-12-23 06:18 UTC by techmannih

related to https://github.com/tscircuit/core/issues/429

2024-12-23 07:49 UTC, seveibar commented
@techmannih i think it's ambiguous if the hole is square or the plating is square, circuit json should be unambiguous so we need to clarify

I'm not sure what @imrishabh18 was thinking about here, but it seems like we need to describe "square plating with circular hole"? Is that right @imrishabh18 ?

I would recommend picking a nice name for "shape", then also adding "hole_shape" and "plating_shape" for clarity

2024-12-23 07:51 UTC, seveibar commented
Square holes are uncommon, so I think rishabh was likely talking about a circular hole with square plating as shown below

![image](https://github.com/user-attachments/assets/d8b5e110-94b0-416b-abed-6eefa9cb61c2)

2024-12-23 07:51 UTC, imrishabh18 commented
Yeah, my fault I should have added the picture in the issue. I was talking about the square plate and circular hole

2024-12-23 07:53 UTC, seveibar commented
this is the first time that we have an ambiguous situation, I'd recommend the shape name to be `shape: "circular_hole_with_square_pad"` and the clarifying `hole_shape: "circle"` and `pad_shape: "square"` to be added

it sounds like overkill but in it will be worth it when the specification is unambiguous!

2024-12-24 19:48 UTC, seveibar requested changes
reread my comments carefully, you didn't address them (not even close- you missed almost all of them?)

2024-12-28 16:45 UTC, seveibar commented on src/pcb/pcb_plated_hole.ts
> +  shape: z.literal("circular_hole_with_square_pad"),
```suggestion
  shape: z.literal("circular_hole_with_rectangular_pad"),
```

2024-12-28 16:45 UTC, seveibar commented on src/pcb/pcb_plated_hole.ts
> +  square_pad_height: z.number(),
```suggestion
  rect_pad_width: z.number(),
  rect_pad_height: z.number(),
```

2024-12-28 16:46 UTC, seveibar commented on src/pcb/pcb_plated_hole.ts
> +  pad_shape: z.literal("square"),
```suggestion
  pad_shape: z.literal("rect"),
```

2024-12-28 16:46 UTC, seveibar commented on src/pcb/pcb_plated_hole.ts
> +const pcb_circular_hole_with_square_plate = z.object({
```suggestion
const pcb_circular_hole_with_rect_pad = z.object({
```

2024-12-28 16:47 UTC, seveibar commented on src/pcb/pcb_plated_hole.ts
> +export interface PcbHoleCircularWithSquarePlated {
```suggestion
export interface PcbHoleCircularWithRectPad {
```

2024-12-28 16:48 UTC, seveibar requested changes
a square always has the same width/height, so it doesn't make sense to define a width and height unless we're doing a redudant definition, but we typically don't do this for rects (we usually just call it a rect and give it a width and height)

2024-12-28 17:47 UTC, seveibar approved these changes

2024-12-28 17:47 UTC, merged